Ext.define("TDK.insentif.pen", {
  extend: "Ext.form.Panel",
  alias: "widget.pen",
  reference: "pen",
  frame: false,
  border: false,
  autoScroll: false,
  layout: "fit",
  items: [
    {
      xtype: "grid",
      pid: "pen",
      emptyText: "No Matching Records",
      autoScroll: true,
      border: true,
      frame: false,
      flex: 1,
      store: {
        fields: [
          { name: "PRDNO", type: "string" },
          { name: "NIK", type: "string" },
          { name: "NAMA", type: "string" },
          { name: "TGL_PERIODE_AWAL", type: "string" },
          { name: "TGL_PERIODE_AKHIR", type: "string" },
          { name: "TGL_AWAL_KERJA", type: "string" },
          { name: "MASA_TAHUN", type: "string" },
          { name: "MASA_BULAN", type: "string" },
          { name: "MASA_HARI", type: "string" },
          { name: "KODE_STKAR", type: "string" },
          { name: "NAMA_STKAR", type: "string" },
          { name: "TGL_STKAR", type: "string" },
          { name: "KODE_JABATAN", type: "string" },
          { name: "NAMA_JABATAN", type: "string" },
          { name: "TGL_JABATAN", type: "string" },
          { name: "KODE_GOLONGAN", type: "string" },
          { name: "NAMA_GOLONGAN", type: "string" },
          { name: "TGL_GOLONGAN", type: "string" },
          { name: "KODE_STKEL", type: "string" },
          { name: "NAMA_STKEL", type: "string" },
          { name: "TGL_STKEL", type: "string" },
          { name: "KODE_COSTCENTER", type: "string" },
          { name: "NAMA_COSTCENTER", type: "string" },
          { name: "MAKER", type: "string" },
          { name: "CARLINE", type: "string" },
          { name: "DLIDL", type: "string" },
          { name: "PAFA", type: "string" },
          { name: "TGL_COSTCENTER", type: "string" },
          { name: "DIVISI", type: "string" },
          { name: "DEPARTMENT", type: "string" },
          { name: "SEKSI", type: "string" },
          { name: "SUBSEKSI", type: "string" },
          { name: "TGL_DEPARTMENT", type: "string" },
          { name: "AREA", type: "string" },
          { name: "SUBAREA", type: "string" },
          { name: "LOKASI", type: "string" },
          { name: "SUBLOKASI", type: "string" },
          { name: "NAMAPROSES", type: "string" },
          { name: "TGL_AREA", type: "string" },
          { name: "KODE_SHIFT", type: "string" },
          { name: "TGL_SHIFT", type: "string" },
          { name: "NOMINAL", type: "float" },
          { name: "BEFORE_PRDNO", type: "string" },
          { name: "BEFORE_NOMINAL", type: "float" },
          { name: "REMARK", type: "string" },
        ],
        autoLoad: true,
        remoteSort: false,
        remoteFilter: false,
        pageSize: 0,
        // proxy: {
        //   type: "ajax",
        //   disableCaching: false,
        //   noCache: false,
        //   actionMethods: { read: "POST" },
        //   url: vconfig.service_api + "formula_insentif/formula_insentif",
        //   extraParams: {
        //     method: "read_insentif",
        //   },
        //   reader: {
        //     type: "json",
        //     rootProperty: "Rows",
        //     totalProperty: "TotalRows",
        //     successProperty: "success",
        //   },
        // },
      },
      plugins: ["filterfield"],
      viewConfig: {
        enableTextSelection: true,
        columnLines: true,
      },
      columns: {
        defaults: {
          sortable: false,
          filter: { xtype: "textfield" },
        },
        items: [
          { xtype: "rownumberer", width: 30, filter: false },
          {
            xtype: "actioncolumn",
            width: 40,
            align: "center",
            menuDisabled: true,
            stopSelection: false,
            sortable: false,
            filter: false,
            items: [
              {
                icon: vconfig.getstyle + "icon/setting.ico",
                tooltip: "Edit Insentif",
                // handler: function (xgrid, rowIndex, colIndex, e, a, rec) {
                //   try {
                //     var layout_pen_insentif = xgrid.up("layout_pen_insentif");
                //     layout_pen_insentif.handler_edit_gaji_pokok(xgrid, rowIndex, colIndex, e, a, rec);
                //   } catch (ex) {
                //     COMP.TipToast.msgbox("Error", ex.message, { cls: "danger", delay: 2000 });
                //   }
                // },
              },
            ],
          },
          { header: "Periode", dataIndex: "PRDNO", width: 80 },
          { header: "NIK", dataIndex: "NIK", width: 80 },
          { header: "Nama", dataIndex: "NAMA", width: 200 },
          { header: 'BPJS TK % JHT', dataIndex: 'BPJS_TK_%_JHT', width: 100, },
          { header: 'BPJS TK % JKM', dataIndex: 'BPJS_TK_%_JKM', width: 100, },
          { header: 'BPJS TK % JKK', dataIndex: 'BPJS_TK_%_JKK', width: 100, },
          { header: 'BPJS TK NILAI JHT', dataIndex: 'BPJS_TK_NILAI_JHT', width: 120, },
          { header: 'BPJS TK NILAI JKM', dataIndex: 'BPJS_TK_NILAI_JKM', width: 120, },
          { header: 'BPJS TK NILAI JKK', dataIndex: 'BPJS_TK_NILAI_JKK', width: 120, },
          { header: 'BPJS TK NILAI TOTAL', dataIndex: 'BPJS_TK_NILAI_TOTAL', width: 120, },
          { header: "Jabatan", dataIndex: "NAMA_JABATAN", width: 110 },
          { header: "Golongan", dataIndex: "NAMA_GOLONGAN", width: 100 },
          { header: "St. Kar", dataIndex: "NAMA_STKAR", width: 80 },
          { header: "St. Kel", dataIndex: "KODE_STKEL", width: 80 },
          { header: "Divisi", dataIndex: "DIVISI", width: 120 },
          { header: "Department", dataIndex: "DEPARTMENT", width: 160 },
          { header: "Seksi", dataIndex: "SEKSI", width: 160 },
          { header: "Subseksi", dataIndex: "SUBSEKSI", width: 160 },
          { header: "Maker", dataIndex: "MAKER", width: 100 },
          { header: "Carline", dataIndex: "CARLINE", width: 100 },
          { header: "DLIDL", dataIndex: "DLIDL", width: 60 },
          { header: "PAFA", dataIndex: "PAFA", width: 80 },
          { header: "Kode Cost", dataIndex: "KODE_COSTCENTER", width: 100 },
          { header: "Cost Center", dataIndex: "NAMA_COSTCENTER", width: 150 },
          { header: "Area", dataIndex: "AREA", width: 100 },
          { header: "Sub Area", dataIndex: "SUBAREA", width: 100 },
          { header: "Lokasi", dataIndex: "LOKASI", width: 100 },
          { header: "Sub Lokasi", dataIndex: "SUBLOKASI", width: 100 },
          { header: "Nama Proses", dataIndex: "NAMAPROSES", width: 100 },
        ],
      },
    },
  ],
  dockedItems: [
    {
      xtype: "toolbar",
      height: 30,
      dock: "top",
      style: {
        background: "rgba(237, 231, 246)",
      },
      items: [
        "->",
        {
          text: "download",
          icon: vconfig.getstyle + "icon/excel.ico",
        },
      ],
    },
    {
      xtype: "toolbar",
      height: 30,
      dock: "bottom",
      style: {
        background: "rgba(237, 231, 246)",
      },
      items: [
        {
          lokasiPage: "insentif.Layoutins",
          columnIndex: "NOMINAL",
          width: 180,
          labelField: "Total Nilai",
        },
        "-",
        {
          lokasiPage: "insentif.Layoutins",
          width: 150,
          labelField: "Total Rows",
        },
      ],
    },
  ],
});
